### ISSUE TITLE
Kernel Panic on Migrating a system restored with xfsdump

### ISSUE THREAD

**Issue by jaawasth** [SUSE/suse-migration-services#208]
Hi Marcus, 

I'm using xfsdump to create backups of RootFS and then restoring my OS with the dump file [a simple test to create a backup and then restore the backup].

Post this when i try to migrate using DMS [to SLES15 SP1] it runs into kernel panic.

it runs in loops and doesn't stop.

I'm attaching whatever output i could get.

[kernel_panic.txt](https://github.com/SUSE/suse-migration-services/files/6440164/kernel_panic.txt)

On a restored system, I have also tried SLES12 SP4 -> SLES12 SP5 migration but that works fine.

Can you please check.

Thanks !!

**Comment by schaefi** [comment]
Sorry there is not much I can help with in this case. It looks like the system is not able to boot because the rootfs is corrupted. The DMS ends in a loop because any attempt to boot up the migration entry ends with a kernel panic. You can go and ask the kernel team for an estimation on the panic output but I don't see this to be related to the DMS system
