### ISSUE TITLE
Provide ssh access to the migration live system

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#26]
Problem Description
================

We agreed that the user who runs the migration will most likely be a skilled system engineer who has an interest to access the live migration system for debugging purposes. Within the scope of the public cloud the following suggestion was made:

* Make sure the live migration image has sshd running
* Implement a service which detects already installed ssh keys from the system to get migrated and make them available on the live migration system
* Add a migration user to the live migration image, such that for debugging a user can login with

   ```
   ssh migration@host
   ```

**Comment by schaefi** [comment]
Just copying the suggestion by @rjschwei 

```
Getting the ssh key?

IMHO we should make the user point us to the ssh key they want to have in place in case something goes wrong, i.e.

zypper migration --major-distro-upgrade --emergency-ssh-key PATH_TO_AUTHORIZED_KEYS_FILE

then we can copy this file into the chroot from where we are running the migration and if something goes wrong the user can login with their ssh key.

Advantage of this approach:

In the public cloud we do not have to go fishing on the metadata server for ssh key information which may or may not be useful to begin with
This works the same in the Public Cloud as it would in the data center
```

**Comment by rjschwei** [comment]
I don't see the need of the initialization code inside the migration system, can you please elaborate?

What the initialization code (cloud-init, azure-agent, compute-engine-init) does, set up a user, network configuration, ssh key copy from the metadata server and other system configurations have already been performed on the instance that is to be upgraded, i.e. all data we could possibly need is already available.

We know that data we need, network setup etc and copy or link that into the migration live system. I see more problems than positives if the initialization code is included and executed.

The work flow is as follows:
- start SLES instance (or have running SLES instance)
- ssh in
- become root
- zypper in major-distro-migration (or whatever the package is going to be named)
- shutdown -r now

During the first step the initialization code runs. In AWS (we use cloud-init) information about the instance is left behind in /var/lib/cloud and the execution of cloud-init is driven by /etc/cloud/cloud.cfg. Neither of these is available (at present) in the migration system. Therefore if cloud-init is available inside the migration system and the user debugging the migration failure decides to run "cloud-init" from the command line cloud-init will be tricked into expecting to do a "first run" configuration. Ina addition since  /etc/cloud/cloud.cfg is not found cloud-init will run the modules that are in the default built in configuration. None of this is desirable and there is a good chance that he migration system just got messed up and the instance is lost for good.

We really need to stay away from enabling the user to use the initialization code inside the migration system it opens a path to big problems.

**Comment by schaefi** [comment]
> We really need to stay away from enabling the user to use the initialization code inside the migration 
> system it opens a path to big problems

agreed, we won't do that. I rephrased the way we want to allow ssh by using the key which already exists as you suggested in the original issue

**Comment by schaefi** [comment]
I've updated the live migration image to contain the ```migration``` user and an sshd setup which allows for key based login method only
