### ISSUE TITLE
multiple base products found

### ISSUE THREAD

**Issue by schaefi** [SUSE/suse-migration-services#63]
During testing of sles-12-sp1-sap-v20170309 in GCE we run into the problem that the product setup failed with the error:

```
[ERROR   ]: 11:25:19 | Base Product update failed with: Found multiple product definitions without element <flavor>: 
/system-root/etc/products.d/SLES_SAP.prod
/system-root/etc/products.d/SLES.prod
```

So those two product files has no flavor set. Products without a flavor are treated as baseproduct but there must only be one of them. Here we have two

I don't know if this is a bug of the product files or if this is something special to SAP.

In any case we should find a solution which requires feedback from people who know more about products.

**Comment by schaefi** [comment]
@ikapelyukhin if you have any insights it would be very helpful. Thanks

**Comment by rjschwei** [comment]
I would like to declare SLES 12 SP1 as out of scope for upgrades with the migration system. People can easily use "zypper migration" on the running system to move to SP3 or SP4. The goal was always to only support distro upgrade from SP4 to SLE 15 only. Now that the SES team has a need for an SP3 to SLE 15 upgrade I am OK with letting the scope creep to include SP3. I am not OK in letting the scope creep as far back as SP1.

**Comment by ikapelyukhin** [comment]
> @ikapelyukhin if you have any insights it would be very helpful. Thanks

Seems like some image build artifact, there shouldn't be two base products.

**Comment by rjschwei** [comment]
> > @ikapelyukhin if you have any insights it would be very helpful. Thanks
> 
> Seems like some image build artifact, there shouldn't be two base products.

Yes, it is an image build artifact triggered by a packaging bug. In SLES 12 SP1 the minimal pattern we use brings with it the SLES product definition. However, since this is a SLES FOr SAP image we also need to install the SLES For SAP product definition. This creates the dual base product problem. Also this creates the file conflict on update. The issue was discovered after the ISO was already done. Therefore there was no way back.

During the recent image refresh I tried to expand the minimal pattern and drop the sles-release in the image build. Needless to say that didn't work. We are stuck with this.

As stated previously I consider a 12 Sp1 -> SLE 15 upgrade out of scope. It also breaks our advertised "skip a service pack" capabilities, SP1 to 15 upgrade would skip 3 service packs.

I am going to close this as out of scope for the project and tool.
