### ISSUE TITLE
Support zypper dup with manual repo setup

### ISSUE THREAD

**Issue by tserong** [SUSE/suse-migration-services#72]
There are some cases where `zypper migration` can't work, for example sites with no direct access to SCC, or with manually configured mirrors/repos, or possibly when using SUMA. I think it makes sense to use `zypper migration` by default, but for cases where the admin knows this is not possible (for whatever reason), can we add a config file to the host system, which would trigger calling `zypper dup` instead? In this case it would be the admin's responsibility to add/remove the necessary repositories before rebooting into the migration system.

**Comment by jesusbv** [comment]
Thank you for the feedback Tim.
Correct me if I got it wrong, so I understood to implement an option inside distribution migration system that will check some options/conditions, and determine whether it can do the migration from version A to B or call ```zypper dup```.

If that is the case, the admin knows is not possible, wouldn't it make sense the admin calls ```zypper dup``` directly ?

**Comment by rjschwei** [comment]
@jesusbv, you are correct that if the admin has to fiddle with the repos manually, i.e. run "zypper ar", this also means the repos are not managed by a service. In this case the admin has to do a whole bunch of work to make sure the repos are consistent. Therefore running "zypper dup" as an additional command after all the other work would appear to be trivial. However, the value the migration service brings is that "zypper dup" would not run on the system to be migrated while that is live.

What often happens when running "zypper dup" on a live system is that services get restarted and then for example network connectivity may get lost. This may interrupt the migration and then requires manual intervention. This cannot happen when we run "zypper dup" from the migration system.

We already have a file, that is currently used as a marker only to enable "debug mode". We can  convert this into a real configuration file. @schaefi you you hit the nail on the head. This happened sooner than I expected ;)

So let's turn `etc/sle-migration-service` into a YAML configuration file. This requires changes to `reboot.py` and `defaults.py` as `get_system_migration_debug_file` should be renamed to `get_system_migration_config_file`.

This would then look as follows:

```
debug: true
migration: dup
```

Where the default for `debug` is `false` and the default for `migration` is `migration`. For the SES case the admin could then put `/etc/sle-migration-service` in place and set `migration: dup` as in the above example.

Let's do the change from marker to config file in one change and then follow up with another PR to support configuration of `zypper dup`

**Comment by tserong** [comment]
@rjschwei that sounds excellent.

**Comment by schaefi** [comment]
I have a clear picture what we need now to implement this and will start to work on it as soon as the open PRs that handles the config file changes are merged

**Comment by schaefi** [comment]
@tserong would be great if you can have a look at #98 

it also deals with the zypper return codes that we will only treat as a warning in case of the migration process. I think you ran into that problem on your first try

Thanks

**Comment by tserong** [comment]
Thanks @schaefi. I did a build with #98 applied, @Martin-Weiss has run it on hardware in `dup` mode, and it went through fine.

**Comment by schaefi** [comment]
>    Thanks [1]@schaefi. I did a build with [2]#98 applied, [3]@Martin-Weiss
>    has run it on hardware in dup mode, and it went through fine.

Great, thanks much for testing
