### ISSUE TITLE
allow specifying product to migrate to

### ISSUE THREAD

**Issue by tserong** [SUSE/suse-migration-services#73]
The current SLES15-Migration image is configured to try to migrate to SLES/15/x86_64 (in /etc/migration-config.yml). Can we make this configurable, via a file on the host system, which would specify the product to migrate to?

Rationale: we can't always just migrate to the latest released product. Here's two examples:

1) We might want to test migrations to an unreleased product.
2) We may be upgrading to a new product, which is older than the latest SLE release (think: some future SUSE Enterprise Storage user, who wants to upgrade from SLE 12 SP3 + SES5.5 to SLE 15 SP1 + SES 6, after SLE 15 SP2 has been released).

**Comment by rjschwei** [comment]
The thinking was that once the user made the jump to the next product, i.e. SLE 12 to SLE 15 the migration to the next SP is trivial via `zypper migration`. This does not hold true for SES agreed and we want to think about how to handle this. However, I do not want to make this available as a general setting. We control the origination point of the migration by providing packages for a given distribution. To cover SES we would make the migration packages available for SLES 12 SP3, but nothing earlier. So a user could not, unless they play tricks and the fall out of support start at SLES 12 GA for example. However, if we make the target generally configurable a user for example could wait until SLES 15 SP4 is released and the try to jump from SLES 12 SP3 all the way to SLES 15 SP4 or later. This is going to create a support and testing nightmare. I oppose going down this road.

Given that for #72 we already create a user configurable file I propose that we enable a target configuration via known keywords. The meaning of the keywords is hard coded in the migration code and we know what they mean. We could add:

```
migration_product: ses
```

to the config file. When `ses` is set we are moving to SLES 15 SP1. The default would be `sles` and we move to SLES 15.

Then is SES moves within the SLES 15 product life cycle, for example SES 7 ends up on SLES 15 SP3, then the SES team would use "regular" migration, i.e. run `zypper migration` on the node rather than using the migration service.

Alternatively we can, as we move along the releases, change the meaning of the `ses` keyword. However that would mean we will have to add some checks somewhere to avoid the "jumping of too many service packs" problem.

@tserong thoughts on using keywords?

**Comment by tserong** [comment]
@rjschwei good point regarding support and testing -- using keywords to lock this down seems reasonable to me.

**Comment by schaefi** [comment]
This is done

@jesusbv please reference the issue number in the commit message such that we can use the auto-close feature of github. Thanks
